spring.config.import=optional:file:./secret.properties

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

nisaba.integrations.bling.client-id=${BLING_CLIENT_ID:}
nisaba.integrations.bling.client-secret=${BLING_CLIENT_SECRET:}

nisaba.integrations.omie.app-key=${OMIE_APP_KEY:}
nisaba.integrations.omie.app-secret=${OMIE_APP_SECRET:}

nisaba.integrations.contaazul.client-id=${CONTAAZUL_CLIENT_ID:}
nisaba.integrations.contaazul.client-secret=${CONTAAZUL_CLIENT_SECRET:}

nisaba.ai.api-key=${AI_API_KEY:}
